# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[2, 4, 6], [4, 6, 8]], [[5, 7, 9], [1, 4, 6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)


((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype,a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 2, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10,size=(7,2))
random_array

array([[3, 0],
       [5, 0],
       [5, 3],
       [8, 8],
       [0, 3],
       [3, 0],
       [4, 7]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float = np.random.random((3,5))
random_float

array([[0.81824055, 0.58678719, 0.85270983, 0.36828288, 0.81704173],
       [0.10459899, 0.95458731, 0.93401607, 0.34018925, 0.2489622 ],
       [0.90098982, 0.18654953, 0.30848   , 0.55338583, 0.07461058]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr2 = np.random.randint(0,10,size = (4,6))
random_arr2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var = np.random.randint(1,10, size = (3,7))
# var

# Find the unique numbers in the array you just created
unique_elements = np.unique(var)
print(unique_elements)

[1 2 3 4 5 7 9]


In [14]:
var

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [15]:
# Find the 0'th index of the latest array you created
zeroth_index = unique_elements[0]
zeroth_index

1

In [16]:
# Get the first 2 rows of latest array you created
var[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
var[:2,:2]

array([[9, 1],
       [5, 3]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_var = np.random.randint(0,10, size=(3,5))
one = np.ones((3,5))
random_var, one


(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [19]:
# Add the two arrays together
new = random_var+one
new

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [20]:
# Create another array of ones of shape (5, 3)
one_2 = np.ones((5,3))
one_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Try add the array of ones and the other most recent array together
new + one_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
one_3 = np.ones((3,5))

In [23]:
# Subtract the new array of ones from the other most recent array
new - one_3

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [24]:
# Multiply the ones array with the latest array
new * (new - one_3)

array([[42., 56.,  6.,  0., 12.],
       [ 2., 56., 12.,  2., 30.],
       [30., 90., 12., 30.,  2.]])

In [25]:
# Take the latest array to the power of 2 using '**'
(new * one_3 ) ** 2

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [26]:
# Do the same thing with np.square()
latest = np.square(new * one_3)
latest

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [27]:
# Find the mean of the latest array using np.mean()
mean_latest = np.mean(latest)
mean_latest

30.333333333333332

In [28]:
# Find the maximum of the latest array using np.max()
np.max(latest)

100.0

In [29]:
# Find the minimum of the latest array using np.min()
np.min(latest)

1.0

In [30]:
# Find the standard deviation of the latest array
std_dev = np.std(latest)
std_dev

27.78168861358543

In [31]:
# Find the variance of the latest array
variance = np.var(latest)
variance

771.8222222222224

In [32]:
# Reshape the latest array to (3, 5, 1)
latest.reshape(3,5,1)

array([[[ 49.],
        [ 64.],
        [  9.],
        [  1.],
        [ 16.]],

       [[  4.],
        [ 64.],
        [ 16.],
        [  4.],
        [ 36.]],

       [[ 36.],
        [100.],
        [ 16.],
        [ 36.],
        [  4.]]])

In [33]:
latest

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [34]:
# Transpose the latest array
latest.T


array([[ 49.,   4.,  36.],
       [ 64.,  64., 100.],
       [  9.,  16.,  16.],
       [  1.,   4.,  36.],
       [ 16.,  36.,   4.]])

What does the transpose do?

In [35]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_1 = np.random.randint(0,10, size=(3,3))
arr_2 = np.random.randint(0,10, size = (3,2))
arr_1, arr_2


(array([[9, 1, 9],
        [3, 7, 6],
        [8, 7, 4]]),
 array([[1, 4],
        [7, 9],
        [8, 8]]))

In [36]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_1, arr_2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [37]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_3= np.random.randint(0,10, size =(4,3))
arr_4 = np.random.randint(0,10, size =(4,3))

In [38]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_3, arr_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

np.dot(arr_3, arr_4.T)


array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_1 = np.random.randint(0,10,(2,3))
arr_2 = np.random.randint(0,10,(2,3))
arr_1, arr_2

(array([[6, 6, 7],
        [4, 2, 7]]),
 array([[5, 2, 0],
        [2, 4, 2]]))

In [41]:
# Compare the two arrays with '>'
arr_1>arr_2

array([[ True,  True,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='
arr_1 >= arr_2


array([[ True,  True,  True],
       [ True, False,  True]])

In [43]:
# Find which elements of the first array are greater than 7
arr_1>7

array([[False, False, False],
       [False, False, False]])

In [44]:
# Which parts of each array are equal? (try using '==')
arr_1 == arr_2

array([[False, False, False],
       [False, False, False]])

In [45]:
# Sort one of the arrays you just created in ascending order
np.sort(arr_1, axis = 1)

array([[6, 6, 7],
       [2, 4, 7]])

In [46]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_1, axis = 1)

array([[0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [49]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(arr_1, axis = 1)
max_index

array([2, 2], dtype=int64)

In [50]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(arr_2, axis = 1)
min_index

array([2, 0], dtype=int64)

In [51]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexs = np.argmax(arr_2, axis = 1)
max_indexs

array([0, 1], dtype=int64)

In [52]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexs = np.argmin(arr_1, axis = 0)
min_indexs

array([1, 1, 0], dtype=int64)

In [53]:
# Create an array of normally distributed random numbers
normal_nos = np.random.normal(size = 10)
normal_nos

array([ 0.36139561,  1.53803657, -0.03582604,  1.56464366, -2.6197451 ,
        0.8219025 ,  0.08704707, -0.29900735,  0.09176078, -1.98756891])

In [55]:
# Create an array with 10 evenly spaced numbers between 1 and 100
even_spaced_nos = np.linspace(1,100, 10)
even_spaced_nos

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.